#ifndef CONSTANTS_H
#define CONSTANTS_H

#define INPUT_ARRAY_STACK 1
#define ADD_ARRAY_STACK 2
#define DELETE_ARRAY_STACK 3
#define PALINDROME_ARRAY_STACK 4
#define PRINT_ARRAY_STACK 5
#define INPUT_LIST_STACK 6
#define ADD_LIST_STACK 7
#define DELETE_LIST_STACK 8
#define PALINDROME_LIST_STACK 9
#define PRINT_LIST_STACK 10
#define END 0
#define START 1

#define MAX_CAPACITY 100
#define PALINDROME 1
#define NO_PALINDROME 0
#endif